import type { Metadata } from "next";
import { Geist, Geist_Mono, Roboto } from "next/font/google";
import "../globals.css";
import { Navigation } from "./_baseblocks/Navigation";
import Script from "next/script";
import { Footer } from "./_components/Footer";


const fontRoboto = Roboto({
  variable: '--font-roboto',
  subsets: ['latin']
});

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${fontRoboto.variable} antialiased bg-base-100`}
      >
        <Navigation />
        {children}
        <Footer /> 
      </body>
    </html>
  );
}
